### ISSUE TITLE
Overview broken after update to gnome-shell 3.36.4

### ISSUE THREAD

**Issue by rudrab** [passingthru67/workspaces-to-dock#208]
###Linux Distribution version
Fedora 32

###Gnome Shell version
gnome-shell-3.36.4-1.fc32.x86_64

###Xorg or Wayland (or both)
Wayland

###Extension version or branch
Latest available in gnome-extension

###Description of the problem
This is an unusual culprit, but with only this extension enabled, when clicking on activities, overview not working properly.
![Screenshot from 2020-07-11 09-47-06](https://user-images.githubusercontent.com/4639447/87222900-970d5c00-c395-11ea-9bc0-85ee4e6aa8c0.png)

###Steps to reproduce the problem
1. Update to latest version of gnome shell
2. click on activities

**Comment by khensunny** [comment]
Same issue. Occurs with the gnome-shell version mentioned above

error message from logs
```
Jul 11 15:22:57 localhost.localdomain gnome-shell[2965]: JS ERROR: TypeError: area is null
                                                         padArea@resource:///org/gnome/shell/ui/workspace.js:1101:9
                                                         _updateWindowPositions@resource:///org/gnome/shell/ui/workspace.js:1334:20
                                                         _realRecalculateWindowPositions@resource:///org/gnome/shell/ui/workspace.js:1311:14
                                                         _recalculateWindowPositions/this._positionWindowsId<@resource:///org/gnome/shell/ui/workspace.js:1286:18
```

**Comment by osirase** [comment]
This appears to be an issue with gnome 3.36.4. Title could be named a lot better, it's quite vague. Maybe something like 'Overview broken after update to gnome-shell 3.36.4'

**Comment by MikeyG** [comment]
Having the same problem after updating my Gentoo system to Gnome 3.36.4.

**Comment by MikeyG** [comment]
The issue may be a problem with gnome-shell, I reverted these changes to the 3.36.4 version of gnome-shell:

workspacesView: Revert commits of !1119
https://gitlab.gnome.org/verdre/gnome-shell/-/commit/836cb974011a19ea2bba16a04c4b4c1a19aaebc6

I recompiled gnome-shell and reinstalled workspaces-to-dock v53 and overview now works.

**Comment by osirase** [comment]
An extension update fixed this issue for me for dash to panel. My workaround was as follows:

Ctrl+alt+F5 or any other tty that isn't serving gnome shell.

`gnome-extensions list --enabled`

Note down the dash to panel extension.

`gnome-extensions disable <extensionName>`

Upon reboot you can now log into gnome and update the extension to the latest version and turn it back on.

**Comment by xakraz** [comment]
@osirase I have tried to update `dash-to-panel` to the latest version (v38 first then master branch)  but it did not solve the issue for me... Have you more details about your work around ?

**Comment by xakraz** [comment]
By the way, these are the errors I get when I enable `workspace-to-dock`:

```
juil. 21 11:09:59 xps-USER gnome-shell[1782]: Usage of object.actor is deprecated for WorkspacesToDock_ShortcutButton
                                                 get@resource:///org/gnome/shell/ui/environment.js:287:29
                                                 _createIcon@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/shortcutsPanel.js:261:13
                                                 _createIconTexture@resource:///org/gnome/shell/ui/iconGrid.js:104:26
                                                 setIconSize@resource:///org/gnome/shell/ui/iconGrid.js:97:14
                                                 _init@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/shortcutsPanel.js:152:19
                                                 _populate@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/shortcutsPanel.js:1289:38
                                                 WorkspacesToDock_ShortcutsPanel@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/shortcutsPanel.js:952:14
                                                 WorkspacesToDock_DockedWorkspaces@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/dockedWorkspaces.js:293:32
                                                 enable@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/extension.js:89:12
                                                 _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:166:32
                                                 _onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:492:18
                                                 _onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:491:11
                                                 _init/createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:529:46
                                                 enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:193:29
                                                 EnableExtension@resource:///org/gnome/shell/ui/shellDBus.js:307:38
                                                 _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:327:38
                                                 _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:404:34
juil. 21 11:09:59 xps-USER gnome-shell[1782]: Usage of object.actor is deprecated for WorkspacesToDock_ShortcutButton
                                                 get@resource:///org/gnome/shell/ui/environment.js:287:29
                                                 _createIcon@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/shortcutsPanel.js:261:13
                                                 _createIconTexture@resource:///org/gnome/shell/ui/iconGrid.js:104:26
                                                 setIconSize@resource:///org/gnome/shell/ui/iconGrid.js:97:14
                                                 _init@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/shortcutsPanel.js:152:19
                                                 _populate@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/shortcutsPanel.js:1289:38
                                                 WorkspacesToDock_ShortcutsPanel@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/shortcutsPanel.js:952:14
                                                 WorkspacesToDock_DockedWorkspaces@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/dockedWorkspaces.js:293:32
                                                 enable@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/extension.js:89:12
                                                 _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:166:32
                                                 _onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:492:18
                                                 _onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:491:11
                                                 _init/createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:529:46
                                                 enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:193:29
                                                 EnableExtension@resource:///org/gnome/shell/ui/shellDBus.js:307:38
                                                 _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:327:38
                                                 _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:404:34
juil. 21 11:09:59 xps-USER gnome-shell[1782]: Usage of object.actor is deprecated for WorkspacesToDock_ShortcutButton
                                                 get@resource:///org/gnome/shell/ui/environment.js:287:29
                                                 _createIcon@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/shortcutsPanel.js:261:13
                                                 _createIconTexture@resource:///org/gnome/shell/ui/iconGrid.js:104:26
                                                 setIconSize@resource:///org/gnome/shell/ui/iconGrid.js:97:14
                                                 _init@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/shortcutsPanel.js:152:19
                                                 _populate@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/shortcutsPanel.js:1289:38
                                                 WorkspacesToDock_ShortcutsPanel@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/shortcutsPanel.js:952:14
                                                 WorkspacesToDock_DockedWorkspaces@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/dockedWorkspaces.js:293:32
                                                 enable@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/extension.js:89:12
                                                 _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:166:32
                                                 _onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:492:18
                                                 _onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:491:11
                                                 _init/createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:529:46
                                                 enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:193:29
                                                 EnableExtension@resource:///org/gnome/shell/ui/shellDBus.js:307:38
                                                 _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:327:38
                                                 _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:404:34
juil. 21 11:09:59 xps-USER gnome-shell[1782]: Usage of object.actor is deprecated for WorkspacesToDock_ShortcutButton
                                                 get@resource:///org/gnome/shell/ui/environment.js:287:29
                                                 _createIcon@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/shortcutsPanel.js:261:13
                                                 _createIconTexture@resource:///org/gnome/shell/ui/iconGrid.js:104:26
                                                 setIconSize@resource:///org/gnome/shell/ui/iconGrid.js:97:14
                                                 _init@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/shortcutsPanel.js:152:19
                                                 _populate@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/shortcutsPanel.js:1289:38
                                                 WorkspacesToDock_ShortcutsPanel@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/shortcutsPanel.js:952:14
                                                 WorkspacesToDock_DockedWorkspaces@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/dockedWorkspaces.js:293:32
                                                 enable@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/extension.js:89:12
                                                 _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:166:32
                                                 _onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:492:18
                                                 _onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:491:11
                                                 _init/createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:529:46
                                                 enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:193:29
                                                 EnableExtension@resource:///org/gnome/shell/ui/shellDBus.js:307:38
                                                 _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:327:38
                                                 _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:404:34
juil. 21 11:09:59 xps-USER gnome-shell[1782]: Usage of object.actor is deprecated for WorkspacesToDock_ShortcutButton
                                                 get@resource:///org/gnome/shell/ui/environment.js:287:29
                                                 _createIcon@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/shortcutsPanel.js:261:13
                                                 _createIconTexture@resource:///org/gnome/shell/ui/iconGrid.js:104:26
                                                 setIconSize@resource:///org/gnome/shell/ui/iconGrid.js:97:14
                                                 _init@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/shortcutsPanel.js:152:19
                                                 _populate@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/shortcutsPanel.js:1289:38
                                                 WorkspacesToDock_ShortcutsPanel@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/shortcutsPanel.js:952:14
                                                 WorkspacesToDock_DockedWorkspaces@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/dockedWorkspaces.js:293:32
                                                 enable@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/extension.js:89:12
                                                 _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:166:32
                                                 _onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:492:18
                                                 _onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:491:11
                                                 _init/createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:529:46
                                                 enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:193:29
                                                 EnableExtension@resource:///org/gnome/shell/ui/shellDBus.js:307:38
                                                 _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:327:38
                                                 _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:404:34
juil. 21 11:09:59 xps-USER gnome-shell[1782]: Usage of object.actor is deprecated for WorkspacesToDock_ShortcutButton
                                                 get@resource:///org/gnome/shell/ui/environment.js:287:29
                                                 _createIcon@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/shortcutsPanel.js:261:13
                                                 _createIconTexture@resource:///org/gnome/shell/ui/iconGrid.js:104:26
                                                 setIconSize@resource:///org/gnome/shell/ui/iconGrid.js:97:14
                                                 _init@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/shortcutsPanel.js:152:19
                                                 _populate@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/shortcutsPanel.js:1289:38
                                                 WorkspacesToDock_ShortcutsPanel@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/shortcutsPanel.js:952:14
                                                 WorkspacesToDock_DockedWorkspaces@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/dockedWorkspaces.js:293:32
                                                 enable@/home/USER/.local/share/gnome-shell/extensions/workspaces-to-dock@passingthru67.gmail.com/extension.js:89:12
                                                 _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:166:32
                                                 _onEnabledExtensionsChanged/<@resource:///org/gnome/shell/ui/extensionSystem.js:492:18
                                                 _onEnabledExtensionsChanged@resource:///org/gnome/shell/ui/extensionSystem.js:491:11
                                                 _init/createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:529:46
                                                 enableExtension@resource:///org/gnome/shell/ui/extensionSystem.js:193:29
                                                 EnableExtension@resource:///org/gnome/shell/ui/shellDBus.js:307:38
                                                 _handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:327:38
                                                 _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:404:34
juil. 21 11:09:59 xps-USER gnome-shell[1782]: Ignoring length property that isn't a number at line 69, col 13
juil. 21 11:09:59 xps-USER gnome-shell[1782]: Ignoring length property that isn't a number at line 69, col 13
juil. 21 11:09:59 xps-USER gnome-shell[1782]: st_widget_get_theme_node called on the widget [0x5608b0d70870 StBin:insensitive] which is not in the stage.
juil. 21 11:09:59 xps-USER gnome-shell[1782]: st_widget_get_theme_node called on the widget [0x5608b0d70870 StBin:insensitive] which is not in the stage.
juil. 21 11:09:59 xps-USER gnome-shell[1782]: Ignoring length property that isn't a number at line 69, col 13
juil. 21 11:09:59 xps-USER gnome-shell[1782]: Ignoring length property that isn't a number at line 69, col 13
juil. 21 11:09:59 xps-USER gnome-shell[1782]: Ignoring length property that isn't a number at line 69, col 13
juil. 21 11:09:59 xps-USER gnome-shell[1782]: Ignoring length property that isn't a number at line 69, col 13
juil. 21 11:09:59 xps-USER gnome-shell[1782]: Ignoring length property that isn't a number at line 69, col 13
juil. 21 11:09:59 xps-USER gnome-shell[1782]: Ignoring length property that isn't a number at line 69, col 13
juil. 21 11:09:59 xps-USER gnome-shell[1782]: Ignoring length property that isn't a number at line 69, col 13
juil. 21 11:09:59 xps-USER gnome-shell[1782]: Ignoring length property that isn't a number at line 69, col 13
juil. 21 11:09:59 xps-USER gnome-shell[1782]: Ignoring length property that isn't a number at line 69, col 13
juil. 21 11:09:59 xps-USER gnome-shell[1782]: Ignoring length property that isn't a number at line 69, col 13
juil. 21 11:09:59 xps-USER gnome-shell[1782]: Ignoring length property that isn't a number at line 69, col 13
juil. 21 11:09:59 xps-USER gnome-shell[1782]: Ignoring length property that isn't a number at line 69, col 13
juil. 21 11:09:59 xps-USER gnome-shell[1782]: Ignoring length property that isn't a number at line 69, col 13
juil. 21 11:09:59 xps-USER gnome-shell[1782]: Ignoring length property that isn't a number at line 69, col 13
juil. 21 11:09:59 xps-USER gnome-shell[1782]: Ignoring length property that isn't a number at line 69, col 13
juil. 21 11:09:59 xps-USER gnome-shell[1782]: Ignoring length property that isn't a number at line 69, col 13
```

**Comment by PrzemekSkw** [comment]
Have the same issue on Endevour OS (arch based) and Gnome ver. 3.36.4.

**Comment by benkj** [comment]
Same problem on debian testing. Solved for now by installing the old shell version from [https://snapshot.debian.org/package/gnome-shell/3.36.3-1/](https://snapshot.debian.org/package/gnome-shell/3.36.3-1/)

**Comment by livchits** [comment]
I have the same issue, I tried the changes of the PR proposed by @RensAlthuis and solved the issue.
Thanks

**Comment by PHLAK** [comment]
I'm having the same issues on Ubuntu 20.04.1 (gnome-shell v3.36.4) as of a day or two ago. Going into overview does not reposition/resize my open windows and the top and bottom are cut off.

![Screenshot 2020-08-11 08:20:23](https://user-images.githubusercontent.com/53531/89915962-da810300-dbab-11ea-89dd-dfc703a52d25.png)

**Comment by ghost** [comment]
Same here on Arch Linux with Gnome 3.36.4, disabling the extension fixes it, re-enabling it break the activities overview again.

**Comment by PrzemekSkw** [comment]
I record gif:
![Peek 2020-08-12 08-41](https://user-images.githubusercontent.com/25219988/89984317-7c225600-dc79-11ea-8f6a-62306a67e7a1.gif)

**Comment by PHLAK** [comment]
FYI, looks like this was already reported as #204

**Comment by MikeyG** [comment]
> The issue may be a problem with gnome-shell, I reverted these changes to the 3.36.4 version of gnome-shell:
> 
> workspacesView: Revert commits of !1119
> https://gitlab.gnome.org/verdre/gnome-shell/-/commit/836cb974011a19ea2bba16a04c4b4c1a19aaebc6
> 
> I recompiled gnome-shell and reinstalled workspaces-to-dock v53 and overview now works.

For Gentoo - gnome shell 3.36.5 fixes the issue.

**Comment by PrzemekSkw** [comment]
I have gnome upgrade today on Endevour OS and now Workspaces to Dock works OK but Dash to Panel broke shell so I must launch Dash to Dock :)

**Comment by rudrab** [comment]
for fedora: update to gnome 3.36.5 solves the issue.

**Comment by RensAlthuis** [comment]
Yeah, seems the folks at gnome reverted the changes that broke so many extensions and all those extensions that were fixed are now broken again :tada: 
Relevant commit: https://github.com/GNOME/gnome-shell/commit/2bf544e2726f238603bb83d6df2f619097028d13
3.36.5 should fix the issue for everyone.

**Comment by tenfourty** [comment]
I'm on Fedora with Gnome 3.36.5 and can still reproduce this issue so I'm not sure it's fixed in Gnome.

**Comment by xakraz** [comment]
Fixed for me with `3.36.5` on Arch
```
OS: Manjaro Linux x86_64 
DE: GNOME 
WM: Mutter 
WM Theme: Adwaita 
```

**Comment by dipunm** [comment]
> 3.36.5 should fix the issue for everyone.

When will Ubuntu get this patch already!?!?! :cry:

**Comment by ajithkumar-natarajan** [comment]
Can anyone say how Gnome 3.36.5 can be installed in Ubuntu?
